name: Github Action to deploy a Node.js app to azure web app

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

        #Add Azure login
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: b01a8043-5bbd-43b5-bed8-9428e4de113e
          tenant-id: 8316e695-7e94-4716-92c4-836cee1dc7ce
          subscription-id: 86325090-0264-4868-9a75-0df86c5f215f

      - name: Verify Azure access
        run: |
          az account show
          az webapp show \
            --name ivan-appservice-lab \
            --resource-group rg-appservice-lab \
            --query "{name:name,state:state,host:name}" \
            -o table

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Create deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-app
          path: |
            .
            #Following will be skipped from the artifact
            !.git
            !.github
            !node_modules

      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: nodejs-app
          path: ./artifact
      
          #Deployment code
      - name: Deploy to Azure Web App - Staging
        uses: azure/webapps-deploy@v3
        with:
          app-name: ivan-appservice-lab
          package: ./artifact

# Test 4