name: Github Action to deploy a Node.js app to azure web app

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Create deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-app
          path: |
            .
            #Following will be skipped from the artifact
            !.git
            !.github
            !node_modules